---
- name: Install ansible pip dependencies
  apt:
    cache_valid_time: 3600
    name: "{{ packages | mandatory }}"
    state: present
  vars:
    packages:
      - python-setuptools
      - virtualenv
      - python3-pip
- name: "Add {{ app_name | mandatory }} user"
  user:
    name: "{{ user_name | mandatory }}"
- name: "Create {{ app_name | mandatory }} application directory"
  file:
    path: "/opt/{{ app_name | mandatory }}"
    state: directory
- name: Create storage directory
  file:
    path: "/var/{{ app_name | mandatory }}"
    owner: "{{ user_name | mandatory }}"
    group: "{{ user_name | mandatory }}"
    state: directory
    mode: 0700
- name: Add Github to known_hosts
  lineinfile:
    dest: "/home/{{ app_name | mandatory }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
- name: "Copy the deploy key, if it is provided"
  when: github_deploy_key is defined
  copy:
    src: "{{ github_deploy_key }}"
    dest: "/home/{{ app_name | mandatory }}/.ssh/id_rsa"
    mode: 0600
- name: "Clone {{ app_name | mandatory }} repo"
  git:
    key_file: "/home/{{ app_name | mandatory if github_deploy_key is not none else omit }}/.ssh/id_rsa"
    repo: "{{ github_repo | mandatory }}"
    dest: "/opt/{{ app_name | mandatory }}"
- name: Install requirements
  pip:
    virtualenv_python: python3
    virtualenv: "/opt/{{ app_name | mandatory }}/venv"
    requirements: "/opt/{{ app_name | mandatory }}/src/requirements.txt"
- name: "Install {{ app_name | mandatory }} service file"
  template:
    src: app.service
    dest: "/etc/systemd/system/{{ app_name | mandatory }}.service"
    mode: 0644
- name: "Setup systemd {{ app_name | mandatory }} service"
  systemd:
    name: "{{ app_name | mandatory }}.service"
    state: restarted
    enabled: yes
    daemon_reload: yes
