---
- import_playbook: utils.yml
- hosts: all
  become: yes
  roles:
    - role: caddy
      vars:
        # caddy_domain_name: ...
    # - role: app
    #   vars:
    #     user_name: ...
    #     app_name: ...
    #     app_description: ...
    #     secrets: .../
    #     github_repo: ...
    #     github_deploy_key: ...
    #     app_environment:
    #       ...
