---
- import_playbook: utils.yml
- hosts: all
  become: yes
  roles:
    - role: caddy
      vars:
        # caddy_domain_name: ...
    - role: app
      # vars:
      #   user_name: ...
      #   app_name: ...
      #   app_description: ...
      #   github_repo: ...
      #   app_environment:
      #     ...
