---
- hosts: all
  become: yes
  tasks:
    - name: Install ansible pip dependencies
      apt:
        name: python-setuptools, virtualenv
        state: present
    - name: Add $APP_NAME user
      user:
        name: $APP_NAME
    - name: Create $APP_NAME application directory
      file:
        path: /opt/$APP_NAME
        state: directory
    - name: Create storage directory
      file:
        path: /var/$APP_NAME
        owner: $APP_NAME
        group: $APP_NAME
        state: directory
        mode: 0700
    - name: Add Github to known_hosts
      become_user: $APP_NAME
      lineinfile:
        dest: /home/$APP_NAME/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"
    - name: Clone $APP_NAME repo
      become_user: root
      git:
        key_file: /home/$APP_NAME/.ssh/id_rsa
        repo: '$APP_REPO'
        dest: /opt/$APP_NAME
    - name: Install requirements
      pip:
        virtualenv_python: python3
        virtualenv: /opt/$APP_NAME/venv
        requirements: /opt/$APP_NAME/src/requirements.txt
    - name: Install $APP_NAME service file
      copy:
        src: app/$APP_NAME.service
        dest: /etc/systemd/system/$APP_NAME.service
        mode: 0644
    - name: Setup systemd $APP_NAME service
      systemd:
        name: $APP_NAME.service
        state: restarted
        enabled: yes
