---
- hosts: all
  become: yes
  tasks:
    - name: Install utilities
      apt:
        cache_valid_time: 3600
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nano
          - vim
          - python3-pip
